version: "3.8"
services:
  postgres:
    image: postgres
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: bookings
    ports:
      - "5432:5432"
    volumes:
      - ./src/data/config/mysql.conf.d :/etc/mysql/mysql.conf.d
      - ./src/data/files:/app/
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    depends_on: 
      - postgres
    volumes:
      - pgadmin_data:/etc/pgadmin_data
volumes:
  pgadmin_data:
